# API Keys Template
# Replace the placeholders with your actual API keys

GEMINI_API_KEY = "YOUR_GEMINI_API_KEY_HERE"
RAPID_API_KEY = "YOUR_RAPID_API_KEY_HERE"
WEATHER_API_KEY = "YOUR_OPENWEATHERMAP_API_KEY_HERE"
GROQ_API_KEY = "YOUR_GROQ_API_KEY_HERE"
AVIATIONSTACK_API_KEY = "YOUR_AVIATIONSTACK_API_KEY_HERE"
